# Generated by Django 5.2.5 on 2025-08-30 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='Date and time of the appointment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the appointment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the appointment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor assigned to the appointment', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient who booked the appointment', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date_time'],
                'unique_together': {('doctor', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Patient symptoms and complaints')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('prescription', models.TextField(blank=True, help_text='Prescribed medications and treatments')),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes')),
                ('blood_pressure', models.CharField(blank=True, help_text='Blood pressure reading (e.g., 120/80)', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Patient weight in kg', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(help_text='Appointment this record is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='mainapp.appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor who conducted the consultation', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_given', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this record belongs to', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text="Patient's date of birth", null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="Patient's gender", max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Patient's blood type", max_length=5)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies (medications, foods, etc.)')),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions and surgeries')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact', max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Relationship to patient (e.g., spouse, parent)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
    ]
